services:
  database:
    container_name: db
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: spring_cache
    image: postgres
    ports:
      - 6965:5432

  my-redis:
    container_name: my-redis
    image: redis
    ports:
      - 6379:6379